### ISSUE TITLE
Windows builds are failing

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/oceans-feedstock#2]
Looks like the issue is with `scipy.io.loadmat`. See https://ci.appveyor.com/project/conda-forge/oceans-feedstock/branch/master/job/91aq87okcprdx1k6

``` shell
===== testing package: oceans-0.2.5-py27_0 ===== 
import: u'oceans'
Traceback (most recent call last): 
  File "C:\conda\conda-bld\test-tmp_dir\run_test.py", line 26, in <module>
    import oceans
  File "C:\conda\envs\_test\lib\site-packages\oceans\__init__.py", line 13, in <module>
    from .datasets import *
  File "C:\conda\envs\_test\lib\site-packages\oceans\datasets\__init__.py", line 1, in <module>
    from .datasets import (woa_subset, woa_profile, etopo_subset, get_depth,
  File "C:\conda\envs\_test\lib\site-packages\oceans\datasets\datasets.py", line 10, in <module>
    from ..ff_tools import get_profile, wrap_lon360
  File "C:\conda\envs\_test\lib\site-packages\oceans\ff_tools\__init__.py", line 1, in <module>
    from .ocfis import *
  File "C:\conda\envs\_test\lib\site-packages\oceans\ff_tools\ocfis.py", line 3, in <module>
    import gsw
  File "C:\conda\envs\_test\lib\site-packages\gsw\__init__.py", line 3, in <module>
    from .gibbs import *
  File "C:\conda\envs\_test\lib\site-packages\gsw\gibbs\__init__.py", line 3, in <module>
    from .earth import *
  File "C:\conda\envs\_test\lib\site-packages\gsw\gibbs\earth.py", line 7, in <module>
    from .conversions import z_from_p
  File "C:\conda\envs\_test\lib\site-packages\gsw\gibbs\conversions.py", line 7, in <module>
    from ..utilities import match_args_return, strip_mask
  File "C:\conda\envs\_test\lib\site-packages\gsw\utilities\__init__.py", line 2, in <module>
    from .utilities import (Bunch, match_args_return, read_data, strip_mask,
  File "C:\conda\envs\_test\lib\site-packages\gsw\utilities\utilities.py", line 9, in <module>
    from scipy.io import loadmat
  File "C:\conda\envs\_test\lib\site-packages\scipy\io\__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "C:\conda\envs\_test\lib\site-packages\scipy\io\matlab\__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "C:\conda\envs\_test\lib\site-packages\scipy\io\matlab\mio.py", line 12, in <module>
    from .miobase import get_matfile_version, docfiller
  File "C:\conda\envs\_test\lib\site-packages\scipy\io\matlab\miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "C:\conda\envs\_test\lib\site-packages\scipy\misc\__init__.py", line 51, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "C:\conda\envs\_test\lib\site-packages\scipy\special\__init__.py", line 627, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found. 
TESTS FAILED: oceans-0.2.5-py27_0
Command exited with code 1
```

**Comment by ocefpaf** [comment]
Fixed in `defaults`.
